import pandas as pd
from sklearn.tree import DecisionTreeClassifier
import m2cgen as m2c

print("Loading telemetry data...")
# 1. Load the training data generated by our C VM
df = pd.read_csv("training_data.csv")

# 2. Split into Features (X) and Target (y)
# X represents what the scheduler knows: CPU operations and IO waits
X = df[["CPU_Ops", "IO_Wait"]]
# y represents what the scheduler wants to predict: The Category (0=CPU heavy, 1=IO heavy)
y = df["Category"]

print("Training Decision Tree...")
# 3. Train the model
# We set max_depth=3 to keep the tree small. A massive tree would
# create huge C code and slow down our OS context switches!
clf = DecisionTreeClassifier(max_depth=3, random_state=42)
clf.fit(X.values, y.values)  # .values strips pandas headers so m2cgen uses raw arrays

print("Transpiling model to C...")
# 4. Convert the trained model into zero-dependency C code
c_code = m2c.export_to_c(clf)

# 5. Save it to be compiled with our VM
with open("model.c", "w") as f:
    f.write(c_code)

print("Success! Model exported to 'model.c'")
